name: Worlds
main: surva\worlds\Worlds
version: 4.0.3
api: 5.0.0

author: survanetwork
description: Easy to use but feature rich World Guard Plugin
website: https://plugins.surva.net/#worlds

commands:
  worlds:
    description: "Worlds plugin main command"
    usage: "/worlds list\n/worlds create <worldname> [type]\n/worlds <remove|load|unload|teleport> <worldname>\n/worlds teleport <player> <worldname>\n/worlds <copy|rename> <from> <to>\n/worlds set\n/worlds set show\n/worlds set permission <permissionstring>\n/worlds set gamemode <survival|creative|adventure|spectator>\n/worlds set <rulename> <true|false>\n/worlds set <rulename> <true|false|white|black>\n/worlds set <rulename> list <add|remove> <item>\n/worlds set <rulename> list <show|reset>\n/worlds unset\n/worlds unset <rulename>\n/worlds defaults\n/worlds defaults show\n/worlds defaults set permission <permissionstring>\n/worlds defaults set gamemode <survival|creative|adventure|spectator>\n/worlds defaults set <rulename> <true|false>\n/worlds defaults set <rulename> <true|false|white|black>\n/worlds defaults set <rulename> list <add|remove> <item>\n/worlds defaults set <rulename> list <show|reset>\n/worlds defaults unset <rulename>"
    permission: worlds.command
    aliases: ["ws"]
permissions:
  worlds.command:
    description: "Use the worlds command"
    default: true
  worlds.list:
    description: "List existing worlds on the server"
    default: true
  worlds.admin:
    description: "Create worlds, delete worlds, set parameters, ..."
    default: op
  worlds.admin.create:
    description: "Create new worlds"
    default: op
  worlds.admin.remove:
    description: "Remove worlds"
    default: op
  worlds.admin.copy:
    description: "Copy worlds"
    default: op
  worlds.admin.rename:
    description: "Rename worlds"
    default: op
  worlds.admin.load:
    description: "Load worlds"
    default: op
  worlds.admin.unload:
    description: "Unload worlds"
    default: op
  worlds.admin.teleport:
    description: "Teleport yourself and other players to any world"
    default: op
  worlds.admin.teleport.self:
    description: "Teleport yourself to any world"
    default: op
  worlds.admin.teleport.others:
    description: "Teleport other players to any world"
    default: op
  worlds.admin.set:
    description: "Set parameters (like gamemode, damage, ...)"
    default: op
  worlds.admin.unset:
    description: "Unset parameters (like gamemode, damage, ...)"
    default: op
  worlds.admin.defaults:
    description: "Set / unset world default values / parameters"
    default: op
  worlds.admin.build:
    description: "Allow building in protected worlds"
    default: op
  worlds.admin.interact:
    description: "Allow interacting in protected worlds"
    default: op
  worlds.admin.command:
    description: "Allow using blocked commands in protected worlds"
    default: op
  worlds.teleport.general:
    description: "Allow teleporting to worlds when having the permission of the specific world"
    default: true
  worlds.special.gamemode:
    description: "Don't change gamemode to world's gamemode (keep it)"
    default: false
  worlds.special.fly:
    description: "Fly in every world"
    default: false
